### ISSUE TITLE
application fails for: gradle run --args=src/main/resources/config.yml

### ISSUE THREAD

**Issue by senivam** [rockarxiv/stream-combiner#1]
I am trying to run the app and it fails:
```
gradle run --args=src/main/resources/config.yml
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :run
[main] INFO  com.homework.streamcombiner.Runner  - Running StreamCombiner with config 'AppConfig(consumerReadTimeout=10, consumerReadTimeoutUnits=SECONDS, xmlConsumerConfigs=[XmlConsumerConfig(host=localhost, port=8088, queueSize=10), XmlConsumerConfig(host=localhost, port=8089, queueSize=10)])'
[ForkJoinPool.commonPool-worker-1] ERROR com.homework.streamcombiner.Runner  - Error connecting to xmlConsumer with config 'XmlConsumerConfig(host=localhost, port=8088, queueSize=10)'
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.homework.streamcombiner.consumer.XmlConsumer.connect(XmlConsumer.java:49)
        at com.homework.streamcombiner.Runner.lambda$main$0(Runner.java:37)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[main] ERROR com.homework.streamcombiner.Runner  - Error connecting to xmlConsumer with config 'XmlConsumerConfig(host=localhost, port=8089, queueSize=10)'
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.homework.streamcombiner.consumer.XmlConsumer.connect(XmlConsumer.java:49)
        at com.homework.streamcombiner.Runner.lambda$main$0(Runner.java:37)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.homework.streamcombiner.Runner.main(Runner.java:44)
[main] INFO  com.homework.streamcombiner.StreamCombiner  - No Data left, stopping StreamCombiner

BUILD SUCCESSFUL in 7s
3 actionable tasks: 3 executed
```

could you please advice?

**Comment by rockarxiv** [comment]
Hi Maxim,

As you see it is trying to connect to configured host:port(localhost:8088, localhost:8089) to get the xmls and then produce json, but as you don't have any XmlProducers running on those host:port it fails to connect. So you need to run some application which will start a server socket and produce xmls and then run streamCombiner. 

Best,
Lyudvig
